### ISSUE TITLE
should truncate output if it's too long

### ISSUE THREAD

**Issue by sunnylqm** [github/webpack-bundlesize-compare-action#204]

**Comment by mattcosta7** [comment]
this may be partially fixed in v1.6.0

We still aren't necessarily truncated, but we've removed much of the output, and hope that helps for now!

**Comment by nskazki** [comment]
@mattcosta7, I'm in the middle of a big migration, and unfortunately, I'm getting this even on v1.6.0.

```
Run github/webpack-bundlesize-compare-action@v1.6.0
Error: Validation Failed: {"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

**Comment by mattcosta7** [comment]
> @mattcosta7, I'm in the middle of a big migration, and unfortunately, I'm getting this even on v1.6.0.
> 
> ```
> Run github/webpack-bundlesize-compare-action@v1.6.0
> Error: Validation Failed: {"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
> ```
> 

Happy to accept prs limiting the output size of the changeset section!

**Comment by mattcosta7** [comment]
> @mattcosta7, I'm in the middle of a big migration, and unfortunately, I'm getting this even on v1.6.0.
> 
> ```
> Run github/webpack-bundlesize-compare-action@v1.6.0
> Error: Validation Failed: {"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
> ```

Give the version from https://github.com/github/webpack-bundlesize-compare-action/pull/301 a shot.  This truncates the output of the `changeset` section to at most 100 files, and should avoid overflowing the comment max length.  We'll work to get that released soon, but you should be able to use that version if you need it!

**Comment by t1mwillis** [comment]
@mattcosta7 I can confirm the PR fixes the issue on my end! Thanks 😄

**Comment by mattcosta7** [comment]
Shipped in https://github.com/github/webpack-bundlesize-compare-action/releases/tag/v1.7.0
