### ISSUE TITLE
Ignore hash in processed filename

### ISSUE THREAD

**Issue by t1mwillis** [github/webpack-bundlesize-compare-action#299]
Consider the attached screenshot from the action, where `app-[hash].js` has been removed but a new `app-[hash].js` has been added. In reality, these are actually the same file for comparison but have a slightly different hash for cache-busting purposes. 

Would it be more true to simply move this down to the **Smaller** section and render a delta?

<img width="776" alt="Screenshot 2023-01-20 at 1 33 48 PM" src="https://user-images.githubusercontent.com/33670137/213809564-ed29fe08-0e1a-4760-b2be-fd872e05348c.png">

**Comment by mattcosta7** [comment]
@t1mwillis I'm not aware, offhand, of a built in way to know how the user has configured their compilation in this regard from the stats object. Given that we can't know easily which hash type the user is using, nor where in the file the hash is, it's a bit difficult to make that change on our side here.  If there is, happy to accept a PR to change it!

If you build without hashes when running comparisons you'll see what you'd expect!

**Comment by t1mwillis** [comment]
You're right, it would probably have to be an action-level parameter to render an "example" filename of some sort. `commons-[hash].js` Maybe I'm fork and see if I can get something working... For now I'll close.
